name: 'Flujo con docker_compose'
on: push
jobs:
  probar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -l
      - name: 'Iniciar docker_compose'
        run: docker_compose -f docker_compose.yml up
      - name: 'Listar los contenedores en ejecuci√≥n'
        run: docker ps -a
      - name: 'Mostrar la bitacora de inicio'
        run: docker logs basedatos
